config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
get "tweets/star" => "tweets#star"
get "tweets/recommend" => "tweets#recommend"
get "tweets/schedule" => "tweets#schedule"
get "tweets/top" => "tweets#top"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :users, only: [:show]
  resources :tweets do
    resources :likes, only: [:create, :destroy]
  end
  root 'tweets#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates_uniqueness_of :tweet_id, scope: :user_id
end

app/models/tweet.rb
class Tweet < ApplicationRecord
 belongs_to :user
 has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :tweets
 has_many :likes, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet
 has_many :tweets, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 
 has_one_attached :image 
def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # サインアップ時にnameのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 def create
    like = current_user.likes.create(tweet_id: params[:tweet_id]) #user_idとtweet_idの二つを代入
    redirect_back(fallback_location: root_path)
  end

  def destroy
    like = Like.find_by(tweet_id: params[:tweet_id], user_id: current_user.id)
    like.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
   before_action :authenticate_user!, only: [:new, :create]
  def index
        @tweets = Tweet.all
  end
  def star
  end
  def recommend
  end
  def schedule 
  end
  def top
  end  
    def new
    @tweet = Tweet.new
  end
  def create
    tweet = Tweet.new(tweet_params)
     tweet.user_id = current_user.id
    if tweet.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
   def show
    @tweet = Tweet.find(params[:id]) 
   end 
    def edit
    @tweet = Tweet.find(params[:id])
   end
    def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end
  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end
  private
  def tweet_params
    params.require(:tweet).permit(:name, :member, :record, :youtube_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(youtube_url)
    if youtube_url.present? && youtube_url[0..16] == "https://youtu.be/"
      return youtube_url[17..27]
      # "https://youtu.be/WGiUk8VakxQ" 11桁のyoutubeのURLが出力されるようにする
    else
      return nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apple</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
 <header>
  <h1>GeekTwitter</h1>
  <div class="header-list">
   <ul>
    <% if user_signed_in? %>
     <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "新規登録", new_user_registration_path %></li>
     <li><%= link_to "ログイン", new_user_session_path %></li>
    <% end %>
   </ul>
  </div>
 </header>
 <main>
  <%= yield %>
 </main>
</body>
</html>

app/views/layouts/new.html.erb
<h1>高校サッカー観戦ガイド</h1>
<h3>新規高校サッカー観戦ガイド</h3>
<%= form_for @高校サッカー観戦ガイド do |f| %>

  <div class="field">
    <%= f.label :項目名 %>
    <%= f.text_field :カラム名, :size => 30 %>
  </div>

# データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :項目名  %>
    <%= f.select :name, 
    [["A", "A"], 
    ["B", "B"], 
    ["C", "C"]], include_blank: "選択して下さい" %>
  </div>

  # データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :項目名  %>
    <%= f.text_area :member, :size => "30x2" %>
  </div>

# データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :項目名  %>
    <%= f.text_area :record, :size => "30x2" %>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :size => 140 %> 
<%= f.label :member %>
  <%= f.text_field :member, :size => 140 %> 
<%= f.label :record %>
  <%= f.text_field :record, :size => 140 %> 
  <%= f.submit "編集する" %>
<% end %>

app/views/tweets/index.html.erb
<h1>高校サッカー</h1>
<h3>guide</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
       <% if t.user.image.attached? %>
     <%= image_tag  t.user.image, size: '50x50'%>
  <% end %>
      <%= t.name %>
      <%= t.member %>
      <%= t.record %>
      <% if t.youtube_url? %>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) if t.youtube_url? %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<% end %> 
<% if user_signed_in? %>
     <% if current_user.already_liked?(t) %>
        <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= t.likes.count %>
        <% end %>
     <% else %>
        <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), data: { turbo_method: :post }  do %>
            <p>いいね</p><%= t.likes.count %>
        <% end %>
     <% end %>
<% else %>
    <p>いいねの数 = </p><%= t.likes.count %>
<% end %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
    </div>
 <%= link_to "編集する", edit_tweet_path(t.id) %>
 <%= button_to "削除する", tweet_path(t.id), method: :delete %>
 </div>  
  <% end %>
</div>
<%= link_to "一覧に戻る", tweets_top_path %>

app/views/tweets/new.html.erb
<h1>注目選手プレー集</h1>
<h3>あ</h3>
<%= form_for @tweet do |f| %>

# データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :項目名 %>
    <%= f.text_field :name, :size => 30 %>
  </div>
  # データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :項目名  %>
    <%= f.text_area :member, :size => "30x2" %>
  </div>

  # データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :項目名  %>
    <%= f.text_area :record, :size => "30x2" %>
  </div>
 <%= f.label :youtube_url %>
    <%= f.text_field :youtube_url, :size => 140 %>
  <%= f.submit "投稿する" %>
<% end %>
<%= link_to "一覧に戻る", tweets_path %>

app/views/tweets/recommend.html.erb
<%= link_to "一覧に戻る", tweets_top_path %>

app/views/tweets/schedule.html.erb
<%= link_to "一覧に戻る", tweets_top_path %>

app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.name %></p>
  <p><%= @tweet.member %></p>
  <p><%= @tweet.record %></p>
  <p><%= @tweet.created_at %></p>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(@tweet.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
<% if user_signed_in? %>
     <% if current_user.already_liked?(@tweet) %>
        <%= link_to tweet_like_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :delete } do %>
            <p>いいねを取り消す</p><%= @tweet.likes.count %>
        <% end %>
     <% else %>
        <%= link_to tweet_likes_path(id: @tweet.id, tweet_id: @tweet.id), data: { turbo_method: :post }  do %>
            <p>いいね</p><%= @tweet.likes.count %>
        <% end %>
     <% end %>
<% else %>
    <p>いいねの数 = </p><%= @tweet.likes.count %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/tweets/star.html.erb
<%= link_to "一覧に戻る", tweets_top_path %>

app/views/tweets/top.html.erb
<h1>高校サッカー</h1>
<h3>guide</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="top">

    <div class="toplink">

        <p><%= link_to "トップページ", tweets_top_path %></p>
        <p><%= link_to "スケジュール", tweets_schedule_path %></p>
        <p><%= link_to "注目高校・選手一覧", tweets_star_path %></p>
        <p><%= link_to "おすすめの見方", tweets_recommend_path %></p>
        <p><%= link_to "プレー集", tweets_path %></p>
    </div>
    <div class="topimg">
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>
<% if @user.image.attached? %>
     <%= image_tag  @user.image, size: '250x200'%>
<% end %>
<!-- 以下はいいね機能を実装している場合-->
<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_tweets.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>